linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 120

linters:
  enable-all: true
  disable:
    - typecheck
    - megacheck
    - gochecknoinits
    - gochecknoglobals
    - unparam

issues:
  max-per-linter: 0
  max-same: 0
